import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit, ViewChild, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Location } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthService } from '../user/auth.service';
interface Car{id:number;name:string;category:string;price:number;image:string;images:string[];seats:number;transmission:string;fuel:string;badge?:string} interface Period{startDate:string;endDate:string} interface Day{date:string;number:number;outside:boolean;past:boolean;unavailable:boolean;selected:boolean;}
declare const L:any;
@Component({selector:'app-reservation-page',imports:[FormsModule,RouterLink],templateUrl:'./reservation-modal.html',styleUrl:'./reservation-modal.scss'})
export class ReservationModal implements OnInit,AfterViewInit,OnDestroy{
 @ViewChild('pickupMap') private pickupMap?:ElementRef<HTMLDivElement>; protected readonly car=signal<Car|null>(null);protected readonly periods=signal<Period[]>([]);protected readonly loading=signal(false);protected readonly pageLoading=signal(true);protected readonly error=signal('');protected readonly success=signal('');protected readonly month=signal(new Date(new Date().getFullYear(),new Date().getMonth(),1));protected readonly activeImage=signal(0);private readonly calendarRevision=signal(0);private map:any;private marker:any;protected files:{cinRecto?:File;cinVerso?:File;permis?:File}={};protected model={phone:'+216 ',pickupMode:'AGENCE',pickupLocation:'Drive Time Elnasr - Avenue Hedi Nouira, Ennasr',pickupLatitude:null as number|null,pickupLongitude:null as number|null,startDate:'',endDate:''};protected readonly days=computed(()=>{this.calendarRevision();return this.makeDays();});protected readonly monthLabel=computed(()=>this.month().toLocaleDateString('fr-FR',{month:'long',year:'numeric'}));
 constructor(private readonly route:ActivatedRoute,private readonly http:HttpClient,private readonly auth:AuthService,private readonly router:Router,private readonly location:Location){}
 ngAfterViewInit(){this.refreshPickupMap();} ngOnDestroy(){this.destroyPickupMap();}
 ngOnInit(){const id=Number(this.route.snapshot.paramMap.get('id'));this.http.get<Car>(`/api/cars/${id}`).pipe(finalize(()=>this.pageLoading.set(false))).subscribe({next:car=>{this.car.set({...car,images:car.images?.length?car.images:[car.image]});this.loadAvailability(car.id);},error:()=>this.error.set('Ce véhicule est introuvable.')});}
 protected dayCount(){if(!this.model.startDate||!this.model.endDate)return 0;return Math.max(1,Math.ceil((new Date(this.model.endDate).getTime()-new Date(this.model.startDate).getTime())/86400000));}protected total(){return this.dayCount()*(this.car()?.price??0);}protected moveMonth(delta:number){const m=this.month();this.month.set(new Date(m.getFullYear(),m.getMonth()+delta,1));const car=this.car();if(car)this.loadAvailability(car.id);}protected refreshCalendar(){this.calendarRevision.update(revision=>revision+1);}protected selectDate(date:string){if(this.isPast(date)||this.isUnavailable(date))return;if(!this.model.startDate||this.model.endDate||date<this.model.startDate.slice(0,10)){this.model.startDate=`${date}T10:00`;this.model.endDate='';}else{this.model.endDate=`${date}T18:00`;}this.refreshCalendar();}protected selectImage(index:number){this.activeImage.set(index);}
 protected goBack(){if(window.history.length>1)this.location.back();else this.router.navigate(['/'],{fragment:'vehicules'});}
 protected choosePickupMode(mode:string){this.model.pickupMode=mode;if(mode==='AGENCE'){this.model.pickupLocation='Drive Time Elnasr - Avenue Hedi Nouira, Ennasr';}else if(mode==='AEROPORT'){this.model.pickupLocation='Aéroport Tunis-Carthage';this.model.pickupLatitude=null;this.model.pickupLongitude=null;}else{this.model.pickupLocation='';this.model.pickupLatitude=null;this.model.pickupLongitude=null;}this.refreshPickupMap();}
 protected choose(key:'cinRecto'|'cinVerso'|'permis',event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file)this.files[key]=file;}
 protected submit(){const car=this.car();if(!car)return;if(!this.auth.currentUser()){this.router.navigate(['/login'],{queryParams:{returnUrl:this.router.url}});return;}if(!this.model.startDate||!this.model.endDate||!this.files.cinRecto||!this.files.cinVerso||!this.files.permis){this.error.set('Complétez les dates et les trois justificatifs.');return;}if(this.model.pickupMode==='DOMICILE'&&(this.model.pickupLatitude===null||this.model.pickupLongitude===null)){this.error.set('Indiquez votre adresse en cliquant sur la carte.');return;}if(this.rangeConflicts()){this.error.set('La période choisie contient des jours indisponibles.');return;}const reservation={carId:car.id,...this.model,startDate:this.toDateTime(this.model.startDate),endDate:this.toDateTime(this.model.endDate)};const data=new FormData();data.append('data',new Blob([JSON.stringify(reservation)],{type:'application/json'}));data.append('cinRecto',this.files.cinRecto);data.append('cinVerso',this.files.cinVerso);data.append('permis',this.files.permis);this.loading.set(true);this.error.set('');this.http.post('/api/reservations',data).pipe(finalize(()=>this.loading.set(false))).subscribe({next:()=>{this.success.set("Demande envoyée. Notre équipe vous appellera pour la confirmer.");this.loadAvailability(car.id);},error:e=>this.error.set(e.error?.message??'Réservation impossible.')});}
 private refreshPickupMap(){setTimeout(()=>{if(!this.pickupMap||typeof L==='undefined')return;this.destroyPickupMap();const agency:[number,number]=[36.8626,10.1879];const center=this.model.pickupMode==='DOMICILE'&&this.model.pickupLatitude!==null&&this.model.pickupLongitude!==null?[this.model.pickupLatitude,this.model.pickupLongitude]:agency;this.map=L.map(this.pickupMap.nativeElement).setView(center,this.model.pickupMode==='DOMICILE'?14:16);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(this.map);const icon=L.icon({iconUrl:'/leaflet/dist/images/marker-icon.png',iconRetinaUrl:'/leaflet/dist/images/marker-icon-2x.png',shadowUrl:'/leaflet/dist/images/marker-shadow.png',iconSize:[25,41],iconAnchor:[12,41],popupAnchor:[1,-34],shadowSize:[41,41]});if(L.Icon?.Default)L.Icon.Default.mergeOptions({iconUrl:'/leaflet/dist/images/marker-icon.png',iconRetinaUrl:'/leaflet/dist/images/marker-icon-2x.png',shadowUrl:'/leaflet/dist/images/marker-shadow.png'});if(this.model.pickupMode==='DOMICILE'){if(this.model.pickupLatitude!==null&&this.model.pickupLongitude!==null)this.marker=L.marker(center,{icon}).addTo(this.map);this.map.on('click',(event:any)=>{this.model.pickupLatitude=event.latlng.lat;this.model.pickupLongitude=event.latlng.lng;this.model.pickupLocation=`Point choisi (${event.latlng.lat.toFixed(5)}, ${event.latlng.lng.toFixed(5)})`;if(this.marker)this.marker.setLatLng(event.latlng);else this.marker=L.marker(event.latlng,{icon}).addTo(this.map);});}else{this.marker=L.marker(agency,{icon}).addTo(this.map).bindPopup('Drive Time Elnasr<br>Avenue Hedi Nouira, Ennasr').openPopup();this.map.on('click',()=>{this.model.pickupLocation='Drive Time Elnasr - Avenue Hedi Nouira, Ennasr';});}setTimeout(()=>this.map?.invalidateSize(),0);},0);}
 private toDateTime(value:string){return value.length===10?`${value}T10:00`:value;}private destroyPickupMap(){if(this.map){this.map.remove();this.map=undefined;this.marker=undefined;}}
 private loadAvailability(carId:number){const m=this.month(),from=this.iso(new Date(m.getFullYear(),m.getMonth(),1)),to=this.iso(new Date(m.getFullYear(),m.getMonth()+1,0));this.http.get<Period[]>(`/api/reservations/availability/${carId}?from=${from}&to=${to}`).subscribe({next:p=>this.periods.set(p),error:()=>this.periods.set([])});}private makeDays():Day[]{const m=this.month(),first=new Date(m.getFullYear(),m.getMonth(),1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));const selectedStart=this.model.startDate.slice(0,10),selectedEnd=this.model.endDate.slice(0,10),today=this.iso(new Date());return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const date=this.iso(d);return{date,number:d.getDate(),outside:d.getMonth()!==m.getMonth(),past:date<today,unavailable:this.isUnavailable(date),selected:date===selectedStart||date===selectedEnd};});}private isPast(date:string){return date<this.iso(new Date());}private isUnavailable(date:string){return this.periods().some(p=>date>=p.startDate&&date<=p.endDate)}private rangeConflicts(){const start=this.model.startDate.slice(0,10),end=this.model.endDate.slice(0,10);return this.periods().some(p=>start<=p.endDate&&end>=p.startDate)}private iso(d:Date){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
}
