import { Component, OnInit, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthService } from '../user/auth.service';
interface Car{id:number;name:string;category:string;price:number;image:string;images:string[];seats:number;transmission:string;fuel:string;badge?:string} interface Period{startDate:string;endDate:string} interface Day{date:string;number:number;outside:boolean;unavailable:boolean;selected:boolean;}
@Component({selector:'app-reservation-page',imports:[FormsModule,RouterLink],templateUrl:'./reservation-modal.html',styleUrl:'./reservation-modal.scss'})
export class ReservationModal implements OnInit{
 protected readonly car=signal<Car|null>(null);protected readonly periods=signal<Period[]>([]);protected readonly loading=signal(false);protected readonly pageLoading=signal(true);protected readonly error=signal('');protected readonly success=signal('');protected readonly month=signal(new Date(new Date().getFullYear(),new Date().getMonth(),1));protected readonly activeImage=signal(0);private readonly calendarRevision=signal(0);protected files:{cinRecto?:File;cinVerso?:File;permis?:File}={};protected model={phone:'+216 ',pickupLocation:'Hammamet',startDate:'',endDate:''};protected readonly days=computed(()=>{this.calendarRevision();return this.makeDays();});protected readonly monthLabel=computed(()=>this.month().toLocaleDateString('fr-FR',{month:'long',year:'numeric'}));
 constructor(private readonly route:ActivatedRoute,private readonly http:HttpClient,private readonly auth:AuthService,private readonly router:Router){}
 ngOnInit(){const id=Number(this.route.snapshot.paramMap.get('id'));this.http.get<Car>(`/api/cars/${id}`).pipe(finalize(()=>this.pageLoading.set(false))).subscribe({next:car=>{this.car.set({...car,images:car.images?.length?car.images:[car.image]});this.loadAvailability(car.id);},error:()=>this.error.set('Ce véhicule est introuvable.')});}
 protected dayCount(){if(!this.model.startDate||!this.model.endDate)return 0;return Math.max(1,Math.ceil((new Date(this.model.endDate).getTime()-new Date(this.model.startDate).getTime())/86400000));}protected total(){return this.dayCount()*(this.car()?.price??0);}protected moveMonth(delta:number){const m=this.month();this.month.set(new Date(m.getFullYear(),m.getMonth()+delta,1));const car=this.car();if(car)this.loadAvailability(car.id);}protected refreshCalendar(){this.calendarRevision.update(revision=>revision+1);}protected selectDate(date:string){if(this.isUnavailable(date))return;if(!this.model.startDate||this.model.endDate||date<this.model.startDate){this.model.startDate=date;this.model.endDate='';}else{this.model.endDate=date;}this.refreshCalendar();}protected selectImage(index:number){this.activeImage.set(index);}
 protected choose(key:'cinRecto'|'cinVerso'|'permis',event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file)this.files[key]=file;}
 protected submit(){const car=this.car();if(!car)return;if(!this.auth.currentUser()){this.router.navigate(['/login'],{queryParams:{returnUrl:this.router.url}});return;}if(!this.model.startDate||!this.model.endDate||!this.files.cinRecto||!this.files.cinVerso||!this.files.permis){this.error.set('Complétez les dates et les trois justificatifs.');return;}if(this.rangeConflicts()){this.error.set('La période choisie contient des jours indisponibles.');return;}const data=new FormData();data.append('data',new Blob([JSON.stringify({carId:car.id,...this.model})],{type:'application/json'}));data.append('cinRecto',this.files.cinRecto);data.append('cinVerso',this.files.cinVerso);data.append('permis',this.files.permis);this.loading.set(true);this.error.set('');this.http.post('/api/reservations',data).pipe(finalize(()=>this.loading.set(false))).subscribe({next:()=>{this.success.set("Demande envoyée. Notre équipe vous appellera pour la confirmer.");this.loadAvailability(car.id);},error:e=>this.error.set(e.error?.message??'Réservation impossible.')});}
 private loadAvailability(carId:number){const m=this.month(),from=this.iso(new Date(m.getFullYear(),m.getMonth(),1)),to=this.iso(new Date(m.getFullYear(),m.getMonth()+1,0));this.http.get<Period[]>(`/api/reservations/availability/${carId}?from=${from}&to=${to}`).subscribe({next:p=>this.periods.set(p),error:()=>this.periods.set([])});}private makeDays():Day[]{const m=this.month(),first=new Date(m.getFullYear(),m.getMonth(),1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const date=this.iso(d);return{date,number:d.getDate(),outside:d.getMonth()!==m.getMonth(),unavailable:this.isUnavailable(date),selected:date===this.model.startDate||date===this.model.endDate};});}private isUnavailable(date:string){return this.periods().some(p=>date>=p.startDate&&date<=p.endDate)}private rangeConflicts(){return this.periods().some(p=>this.model.startDate<=p.endDate&&this.model.endDate>=p.startDate)}private iso(d:Date){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
}
