import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthService } from './auth.service';

interface Car { id:number; name:string; category:string; price:number; seats:number; transmission:string; fuel:string; badge?:string; image:string; images:string[]; imageFileIds?:string[]; }
@Component({selector:'app-admin-cars',imports:[FormsModule,RouterLink],templateUrl:'./admin-cars.html',styleUrl:'./admin-cars.scss'})
export class AdminCars implements OnInit {
 protected readonly cars=signal<Car[]>([]);protected readonly loading=signal(false);protected readonly loadingCars=signal(true);protected readonly deletingId=signal<number|null>(null);protected readonly error=signal('');protected readonly success=signal('');protected selectedFiles:(File|null)[]=[];protected imagePreviews:string[]=[];protected imageFileIds:string[]=[];protected editingCarId:number|null=null;protected model=this.emptyModel();
 constructor(private readonly http:HttpClient,protected readonly auth:AuthService,private readonly router:Router){} ngOnInit(){this.load();}
 protected load(){this.loadingCars.set(true);this.http.get<Car[]>('/api/cars').pipe(finalize(()=>this.loadingCars.set(false))).subscribe({next:cars=>this.cars.set(cars),error:()=>this.error.set('Le catalogue est momentanément indisponible.')});}
 protected chooseImages(event:Event){const input=event.target as HTMLInputElement;const files=Array.from(input.files??[]);if(!files.length)return;if(files.some(file=>!file.type.startsWith('image/'))){this.error.set('Sélectionnez uniquement des images.');input.value='';return;}const availableSlots=8-this.selectedFiles.length;const filesToAdd=files.slice(0,availableSlots);this.selectedFiles.push(...filesToAdd);this.imagePreviews.push(...filesToAdd.map(file=>URL.createObjectURL(file)));this.imageFileIds.push(...filesToAdd.map(()=>''));this.error.set(filesToAdd.length<files.length?'Vous pouvez ajouter 8 images maximum.':'');input.value='';}
 protected setCover(index:number){if(index===0)return;const [file]=this.selectedFiles.splice(index,1);const [preview]=this.imagePreviews.splice(index,1);const [fileId]=this.imageFileIds.splice(index,1);this.selectedFiles.unshift(file);this.imagePreviews.unshift(preview);this.imageFileIds.unshift(fileId);}
 protected removePreview(index:number){if(this.selectedFiles[index])URL.revokeObjectURL(this.imagePreviews[index]);this.selectedFiles.splice(index,1);this.imagePreviews.splice(index,1);this.imageFileIds.splice(index,1);}
 protected edit(car:Car){this.editingCarId=car.id;this.model={name:car.name,category:car.category,price:car.price,seats:car.seats,transmission:car.transmission,fuel:car.fuel,badge:car.badge??''};this.selectedFiles=(car.images??[car.image]).map(()=>null);this.imagePreviews=car.images?.length?car.images:[car.image];this.imageFileIds=car.imageFileIds??[];while(this.imageFileIds.length<this.imagePreviews.length)this.imageFileIds.push('');this.error.set('');this.success.set('');}
 protected cancelEdit(){this.editingCarId=null;this.model=this.emptyModel();this.selectedFiles=[];this.clearPreviews();}
 protected submit(){if(!this.selectedFiles.length){this.error.set('Ajoutez au moins une photo du véhicule.');return;}const wasEditing=this.editingCarId!==null;const data=new FormData();Object.entries(this.model).forEach(([key,value])=>data.append(key,String(value)));const newFiles=this.selectedFiles.filter((file):file is File=>file!==null);newFiles.forEach(file=>data.append('images',file));if(wasEditing){this.imageFileIds.filter(Boolean).forEach(fileId=>data.append('keepImageFileIds',fileId));const coverId=this.imageFileIds[0];if(coverId)data.append('coverImageFileId',coverId);else data.append('coverNewIndex',String(newFiles.indexOf(this.selectedFiles[0] as File)));}this.loading.set(true);this.error.set('');this.success.set('');const request=wasEditing?this.http.put<Car>(`/api/admin/cars/${this.editingCarId}`,data):this.http.post<Car>('/api/admin/cars',data);request.pipe(finalize(()=>this.loading.set(false))).subscribe({next:car=>{this.cars.update(cars=>wasEditing?cars.map(item=>item.id===car.id?car:item):[car,...cars]);this.editingCarId=null;this.model=this.emptyModel();this.clearPreviews();this.success.set(`${car.name} a été ${wasEditing?'modifié':'ajouté'} avec succès.`);},error:error=>this.error.set(error.error?.detail??error.error?.message??"Échec de l'enregistrement du véhicule.")});}
 protected remove(car:Car){if(!confirm(`Supprimer définitivement ${car.name} et toutes ses images ?`))return;this.deletingId.set(car.id);this.http.delete(`/api/admin/cars/${car.id}`).pipe(finalize(()=>this.deletingId.set(null))).subscribe({next:()=>{this.cars.update(cars=>cars.filter(item=>item.id!==car.id));this.success.set(`${car.name} a été supprimé.`);},error:()=>this.error.set('La suppression du véhicule a échoué.')});}
 protected logout(){this.auth.logout();this.router.navigateByUrl('/login');} private clearPreviews(){this.selectedFiles.forEach((file,index)=>{if(file)URL.revokeObjectURL(this.imagePreviews[index]);});this.selectedFiles=[];this.imagePreviews=[];this.imageFileIds=[];} private emptyModel(){return{name:'',category:'Citadine',price:90,seats:5,transmission:'Manuelle',fuel:'Essence',badge:''};}
}
