package com.fmrent.reservations.service;
import com.fmrent.reservations.dto.*; import com.fmrent.reservations.model.Reservation; import com.fmrent.reservations.repository.ReservationRepository; import java.math.BigDecimal; import java.time.*; import java.util.List; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.client.RestClient; import org.springframework.web.multipart.MultipartFile;
@Service public class ReservationService {private final ReservationRepository repository;private final PrivateDocumentService documents;private final RestClient cars;
 public ReservationService(ReservationRepository repository,PrivateDocumentService documents,@Value("${services.cars-url}")String url){this.repository=repository;this.documents=documents;this.cars=RestClient.builder().baseUrl(url).build();}
 @Transactional public Reservation create(CreateReservationRequest r,MultipartFile cinRecto,MultipartFile cinVerso,MultipartFile permis,String email){if(r.endDate().isBefore(r.startDate()))throw new IllegalArgumentException("La date de retour doit suivre la date de départ.");validatePickup(r);if(!repository.conflicts(r.carId(),r.startDate(),r.endDate()).isEmpty())throw new IllegalArgumentException("Ce véhicule n'est pas disponible pour cette période.");CarDto car=cars.get().uri("/api/cars/{id}",r.carId()).retrieve().body(CarDto.class);if(car==null)throw new IllegalArgumentException("Véhicule introuvable.");String rectoId=documents.upload(cinRecto,"cin-recto");String versoId=documents.upload(cinVerso,"cin-verso");String permisId=documents.upload(permis,"permis");long days=Math.max(1,(long)Math.ceil(Duration.between(r.startDate(),r.endDate()).toHours()/24.0));return repository.save(new Reservation(car.id(),car.name(),car.image(),email,r.phone(),r.pickupLocation(),r.pickupMode(),r.pickupLatitude(),r.pickupLongitude(),r.startDate(),r.endDate(),car.price().multiply(BigDecimal.valueOf(days)),rectoId,versoId,permisId));}
 private void validatePickup(CreateReservationRequest r){if("DOMICILE".equals(r.pickupMode())&&(r.pickupLatitude()==null||r.pickupLongitude()==null||r.pickupLatitude()<-90||r.pickupLatitude()>90||r.pickupLongitude()<-180||r.pickupLongitude()>180))throw new IllegalArgumentException("Sélectionnez votre adresse sur la carte.");if(!"DOMICILE".equals(r.pickupMode())&&(r.pickupLatitude()!=null||r.pickupLongitude()!=null))throw new IllegalArgumentException("Les coordonnées ne sont valides que pour une prise en charge à domicile.");}
 public List<UnavailablePeriod> availability(Long carId,LocalDate from,LocalDate to){return repository.conflicts(carId,from.atStartOfDay(),to.plusDays(1).atStartOfDay().minusNanos(1)).stream().map(r->new UnavailablePeriod(r.getStartDate().toLocalDate(),r.getEndDate().toLocalDate())).toList();}
 public List<Reservation> mine(String email){return repository.findByUserEmailOrderByCreatedAtDesc(email);} public List<Reservation> all(){return repository.findAllByOrderByCreatedAtDesc();}
 @Transactional public Reservation approve(Long id){Reservation reservation=repository.findById(id).orElseThrow(()->new IllegalArgumentException("Réservation introuvable."));reservation.approve();return reservation;}
 @Transactional public void delete(Long id){Reservation reservation=repository.findById(id).orElseThrow(()->new IllegalArgumentException("Réservation introuvable."));documents.delete(reservation.getCinRectoFileId());documents.delete(reservation.getCinVersoFileId());documents.delete(reservation.getPermisFileId());repository.delete(reservation);}}
