CREATE TABLE reservations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,car_id BIGINT NOT NULL,car_name VARCHAR(120) NOT NULL,car_image VARCHAR(500) NOT NULL,user_email VARCHAR(190) NOT NULL,phone VARCHAR(30) NOT NULL,pickup_location VARCHAR(150) NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,total_price DECIMAL(10,2) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'PENDING',created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),approved_at TIMESTAMP(6));

CREATE INDEX idx_reservation_user ON reservations(user_email);
CREATE INDEX idx_reservation_status ON reservations(status);
