package com.fmrent.reservations.model;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*;
@Entity @Table(name="reservations") public class Reservation {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @Column(nullable=false) private Long carId; @Column(nullable=false,length=120) private String carName; @Column(nullable=false,length=500) private String carImage;
 @Column(nullable=false,length=190) private String userEmail; @Column(nullable=false,length=30) private String phone; @Column(nullable=false,length=150) private String pickupLocation; @Column(nullable=false,length=20) private String pickupMode; private Double pickupLatitude; private Double pickupLongitude;
 @Column(nullable=false,length=120) private String cinRectoFileId; @Column(nullable=false,length=120) private String cinVersoFileId; @Column(nullable=false,length=120) private String permisFileId;
 @Column(nullable=false) private LocalDateTime startDate; @Column(nullable=false) private LocalDateTime endDate; @Column(nullable=false,precision=10,scale=2) private BigDecimal totalPrice;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=20) private ReservationStatus status=ReservationStatus.PENDING; @Column(nullable=false,updatable=false) private Instant createdAt=Instant.now(); private Instant approvedAt;
 protected Reservation(){} public Reservation(Long carId,String carName,String carImage,String userEmail,String phone,String pickupLocation,String pickupMode,Double pickupLatitude,Double pickupLongitude,LocalDateTime startDate,LocalDateTime endDate,BigDecimal totalPrice,String cinRectoFileId,String cinVersoFileId,String permisFileId){this.carId=carId;this.carName=carName;this.carImage=carImage;this.userEmail=userEmail;this.phone=phone;this.pickupLocation=pickupLocation;this.pickupMode=pickupMode;this.pickupLatitude=pickupLatitude;this.pickupLongitude=pickupLongitude;this.startDate=startDate;this.endDate=endDate;this.totalPrice=totalPrice;this.cinRectoFileId=cinRectoFileId;this.cinVersoFileId=cinVersoFileId;this.permisFileId=permisFileId;}
 public Long getId(){return id;} public Long getCarId(){return carId;} public String getCarName(){return carName;} public String getCarImage(){return carImage;} public String getUserEmail(){return userEmail;} public String getPhone(){return phone;} public String getPickupLocation(){return pickupLocation;} public String getPickupMode(){return pickupMode;} public Double getPickupLatitude(){return pickupLatitude;} public Double getPickupLongitude(){return pickupLongitude;} public LocalDateTime getStartDate(){return startDate;} public LocalDateTime getEndDate(){return endDate;} public BigDecimal getTotalPrice(){return totalPrice;} @JsonIgnore public String getCinRectoFileId(){return cinRectoFileId;} @JsonIgnore public String getCinVersoFileId(){return cinVersoFileId;} @JsonIgnore public String getPermisFileId(){return permisFileId;} public ReservationStatus getStatus(){return status;} public Instant getCreatedAt(){return createdAt;} public Instant getApprovedAt(){return approvedAt;}
 public void approve(){status=ReservationStatus.APPROVED;approvedAt=Instant.now();}
}
