server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ${RESERVATION_DATABASE_URL}
    username: ${RESERVATION_DATABASE_USERNAME}
    password: ${RESERVATION_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: reservations_service
  flyway:
    enabled: true
    table: flyway_schema_history
    schemas: reservations_service
    default-schema: reservations_service
    create-schemas: true
management:
  endpoints:
    web:
      exposure:
        include: health
jwt:
  secret: ${JWT_SECRET}
services:
  cars-url: ${CARS_SERVICE_URL:http://localhost:8081}
imagekit:
  private-key: ${IMAGEKIT_PRIVATE_KEY}
